
# This Vagrant script creates a Web App virtual machine on Virtualbox.
# Vagrantfile API/syntax version
VAGRANTFILE_API_VERSION = "2"
WEB_APP_SERVER_IP = "192.168.56.130"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  # Web Application server, nodewa
  config.vm.define 'nodewa' do |webapp|
    webapp.vm.box = 'ubuntu/impish64'
    webapp.vm.hostname = 'iserverwa'
    webapp.vm.network "private_network", ip: WEB_APP_SERVER_IP, hostname: true
    webapp.vm.network "forwarded_port", guest: 8000, host: 8080
    # Configure VM
    webapp.vm.provider 'virtualbox' do |vb, override|
      vb.name = "iservervmwa"
      vb.memory = '1024'
      vb.cpus = 1
    end
    # Install and start WebApp
    webapp.vm.provision "shell", path: "installresources.sh"
  end
end
